import type {Metadata} from "next";
import "./globals.css";
import NavigationBar from "@/components/NavBar/NavigationBar";
import Footer from "@/components/Footer/Footer";
import {BasketProvider} from "@/context/basketContext";

export const metadata: Metadata = {
    title: "EMIT Event",
    description: "Generated by Arbabiun",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className="bg-[#0B253A]">
        <link rel="icon" href="/icon.png"/>
        <BasketProvider>
            <NavigationBar/>
                {children}
            <Footer/>
        </BasketProvider>
        </body>
        </html>
    )
        ;
}
