import type {Metadata} from "next";
import "./globals.css";
import Head from "next/head";
import NavigationBar from "@/components/NavBar/NavigationBar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
    title: "EMIT",
    description: "Generated by Arbabiun",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className="bg-violet-950"
        >
        <Head>
            <link rel="icon" href="/favicon.svg" type="image/svg+xml"/>
        </Head>
        <NavigationBar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
