import type {Metadata} from "next";
import "./globals.css";
import NavigationBar from "@/components/NavBar/NavigationBar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
    title: "EMIT Event",
    description: "Generated by Arbabiun",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
        <body className="bg-violet-950">
        <link rel="icon" href="/icon.svg"/>
        <NavigationBar/>
        {children}
        <Footer/>
        </body>
        </html>
    )
        ;
}
